repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Rust Format
        entry: bash -c 'cd src-tauri && cargo fmt'
        language: system
        files: \.rs$
        pass_filenames: false
        description: Format Rust code with rustfmt

      - id: cargo-clippy
        name: Rust Clippy
        entry: bash -c 'cd src-tauri && cargo clippy --all-targets --all-features -- -D warnings'
        language: system
        files: \.rs$
        pass_filenames: false
        description: Run Rust clippy linter

      - id: cargo-test
        name: Rust Tests
        entry: bash -c 'cd src-tauri && cargo test'
        language: system
        files: \.rs$
        pass_filenames: false
        description: Run Rust tests

      - id: cleanup-builds
        name: Cleanup Old Builds
        entry: bash -c 'if [ -f scripts/cleanup-builds.sh ]; then ./scripts/cleanup-builds.sh 3; fi'
        language: system
        files: Cargo\.(toml|lock)$
        pass_filenames: false
        description: Clean up old Rust build artifacts
        stages: [pre-push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        description: Trim trailing whitespace

      - id: end-of-file-fixer
        description: Ensure files end with a newline

      - id: check-merge-conflict
        description: Check for merge conflict markers

      - id: check-yaml
        description: Check YAML file syntax

      - id: check-json
        description: Check JSON file syntax
        exclude: tsconfig\.json$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        description: Format JavaScript, TypeScript, CSS, and Markdown files
        files: \.(js|jsx|ts|tsx|css|scss|md|json|html)$
        exclude: |
          (?x)^(
            pnpm-lock\.yaml|
            dist/.*|
            node_modules/.*
          )$
