#!/bin/bash

# DictaClerk alias installation script for disk space management
# Usage: ./scripts/setup-aliases.example.sh
#
# This script configures custom bash aliases to facilitate development
# Copy this file and adapt it to your needs:
# cp scripts/setup-aliases.example.sh scripts/setup-aliases.sh

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ALIAS_FILE="$HOME/.dicta_clerk_aliases"

echo "🔧 Installing DictaClerk aliases..."

# Create alias file with correct paths
cat > "$ALIAS_FILE" << EOF
# Aliases for DictaClerk - Disk space management
# Automatically generated by scripts/setup-aliases.sh
# Project: $PROJECT_ROOT

# Quick cleanup
alias dcclean='cd "$PROJECT_ROOT" && ./scripts/cleanup-builds.sh'
alias dcclean-full='cd "$PROJECT_ROOT/src-tauri" && cargo clean'

# Disk space monitoring
alias dcsize='echo "Shared target:" && du -sh /tmp/rust-builds/dicta-clerk 2>/dev/null || echo "No builds"; echo "Cargo cache:" && du -sh ~/.cargo 2>/dev/null'

# Optimized builds
alias dcbuild='cd "$PROJECT_ROOT/src-tauri" && cargo check'
alias dcbuild-release='cd "$PROJECT_ROOT/src-tauri" && cargo build --release'
alias dctest='cd "$PROJECT_ROOT/src-tauri" && cargo test'

# Cleanup with different retention periods
alias dcclean-week='cd "$PROJECT_ROOT" && ./scripts/cleanup-builds.sh 7'
alias dcclean-month='cd "$PROJECT_ROOT" && ./scripts/cleanup-builds.sh 30'

# Development
alias dcfmt='cd "$PROJECT_ROOT/src-tauri" && cargo fmt'
alias dclint='cd "$PROJECT_ROOT/src-tauri" && cargo clippy'
alias dcdev='cd "$PROJECT_ROOT" && npm run tauri dev'

# Git helpers
alias dcstatus='cd "$PROJECT_ROOT" && git status'
alias dclog='cd "$PROJECT_ROOT" && git log --oneline -10'

# Optimization information
alias dcinfo='echo "📊 DictaClerk optimization configuration:" && echo "  - Project: $PROJECT_ROOT" && echo "  - Shared target: /tmp/rust-builds/dicta-clerk" && echo "  - Cleanup script: ./scripts/cleanup-builds.sh" && echo "  - Automatic git hooks enabled" && echo "  - cargo-sweep and cargo-cache installed" && echo "" && echo "Available commands:" && echo "  dcclean      - Standard cleanup (7 days)" && echo "  dcclean-full - Complete cleanup" && echo "  dcsize       - Check disk usage" && echo "  dcbuild      - Fast build (check)" && echo "  dctest       - Run tests" && echo "  dcfmt        - Format code" && echo "  dclint       - Lint (clippy)" && echo "  dcdev        - Development mode" && echo "  dcinfo       - This help"'
EOF

echo "✅ Alias file created: $ALIAS_FILE"

# Check if aliases are already sourced in .bashrc
if ! grep -q "source.*dicta_clerk_aliases" "$HOME/.bashrc" 2>/dev/null; then
    echo ""
    echo "📝 To activate aliases, add this line to your ~/.bashrc:"
    echo "source $ALIAS_FILE"
    echo ""
    read -p "Do you want me to add it automatically? (y/N): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "" >> "$HOME/.bashrc"
        echo "# DictaClerk aliases - $(date)" >> "$HOME/.bashrc"
        echo "if [ -f $ALIAS_FILE ]; then" >> "$HOME/.bashrc"
        echo "    source $ALIAS_FILE" >> "$HOME/.bashrc"
        echo "fi" >> "$HOME/.bashrc"
        echo "✅ Added to ~/.bashrc"
    fi
else
    echo "✅ Aliases are already configured in ~/.bashrc"
fi

echo ""
echo "🎉 Installation complete!"
echo "🔄 Reload your terminal or type: source ~/.bashrc"
echo ""
echo "💡 Tip: type 'dcinfo' to see all available commands"
echo ""
echo "📚 Complete documentation: docs/DISK_SPACE_OPTIMIZATION.md"
